name: shopyo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  animate_do: ^4.2.0
  build_runner: ^2.9.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  flutter_zoom_drawer: ^3.2.0
  fluttertoast: ^9.0.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  googleapis_auth: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  json_serializable: ^6.11.1
  permission_handler: ^12.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.7.3
  retrofit_generator: ^10.0.6
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/app_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icons/play_store_512.png"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.dev
    - .env.prod
    - service-account.json
    - assets/images/core/
    - lang/ar.json
    - lang/en.json
    - assets/images/core/
    - assets/images/admin/
    - assets/images/customer/
    - assets/svg/
  fonts:
    # Arabic Font
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400
    # English Font
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400

## dart run build_runner build --delete-conflicting-outputs
